export const BREAD_CRUMB_MAP: Record<string, string[]> = {
    "/admin": ["Admin", "Dashboard"],
    "/admin/users": ["Admin", "Tài khoản"],
    "/admin/approvals": ["Admin", "Phê duyệt"],
    "/admin/internal-staff": ["Admin", "Nhân sự nội bộ"],
    "/admin/roles": ["Admin", "Phân quyền"],
    "/admin/transactions": ["Admin", "Giao dịch"],
    "/admin/delivery": ["Admin", "Điều phối giao hàng"],
    "/admin/operations": ["Admin", "Đóng gói & giao hàng"],
    "/admin/moderation": ["Admin", "Kiểm duyệt sản phẩm"],
    "/admin/feedbacks": ["Admin", "Phản hồi"],
    "/admin/reports": ["Admin", "Báo cáo"],
    "/admin/settings": ["Admin", "Cấu hình hệ thống"],

    "/supermarketStaff/dashboard": ["SupermarketStaff", "Tổng quan"],
    "/supermarketStaff/products": ["SupermarketStaff", "Sản phẩm"],
    "/supermarketStaff/products/add": ["SupermarketStaff", "Sản phẩm", "Thêm sản phẩm"],
    "/supermarketStaff/products/edit": ["SupermarketStaff", "Sản phẩm", "Chỉnh sửa"],
    "/supermarketStaff/statistic": ["SupermarketStaff", "Thống kê"],
    "/supermarketStaff/profile": ["SupermarketStaff", "Hồ sơ"],
    "/supermarketStaff/notification": ["SupermarketStaff", "Thông báo"],
    "/supermarketStaff/setting": ["SupermarketStaff", "Cài đặt"],
}
