export const BREAD_CRUMB_MAP: Record<string, string[]> = {
    "/admin": ["Admin", "Tổng quan"],
    "/admin/users": ["Admin", "Tài khoản"],
    "/admin/approvals": ["Admin", "Phê duyệt"],
    "/admin/internal-staff": ["Admin", "Nhân sự nội bộ"],
    "/admin/transactions": ["Admin", "Giao dịch"],
    "/admin/delivery": ["Admin", "Điều phối giao hàng"],
    "/admin/operations": ["Admin", "Đóng gói & giao hàng"],
    "/admin/feedbacks": ["Admin", "Phản hồi"],
    "/admin/reports": ["Admin", "Báo cáo"],
    "/admin/settings": ["Admin", "Cấu hình hệ thống"],

    "/supermarketStaff/dashboard": ["SupermarketStaff", "Tổng quan"],
    "/supermarketStaff/products": ["SupermarketStaff", "Sản phẩm"],
    "/supermarketStaff/products/add": ["SupermarketStaff", "Sản phẩm", "Thêm sản phẩm"],
    "/supermarketStaff/products/edit": ["SupermarketStaff", "Sản phẩm", "Chỉnh sửa"],
    "/supermarketStaff/statistic": ["SupermarketStaff", "Thống kê"],
    "/supermarketStaff/profile": ["SupermarketStaff", "Hồ sơ"],
    "/supermarketStaff/notification": ["SupermarketStaff", "Thông báo"],
    "/supermarketStaff/setting": ["SupermarketStaff", "Cài đặt"],

    "/package/dashboard": ["PackagingStaff", "Tổng quan"],
    "/package/orders": ["PackagingStaff", "Đơn chờ đóng gói"],
    "/package/collect": ["PackagingStaff", "Thu gom sản phẩm"],
    "/package/packing": ["PackagingStaff", "Hoàn tất đóng gói"],
    "/package/reports": ["PackagingStaff", "Báo cáo"],
    "/package/notification": ["PackagingStaff", "Thông báo"],
    "/package/profile": ["PackagingStaff", "Hồ sơ"],
    "/package/setting": ["PackagingStaff", "Cài đặt"],
}
