export const BREAD_CRUMB_MAP: Record<string, string[]> = {
    "/admin": ["Admin", "Dashboard"],
    "/admin/users": ["Admin", "Tài khoản"],
    "/admin/approvals": ["Admin", "Phê duyệt"],
    "/admin/internal-staff": ["Admin", "Nhân sự nội bộ"],
    "/admin/roles": ["Admin", "Phân quyền"],
    "/admin/transactions": ["Admin", "Giao dịch"],
    "/admin/delivery": ["Admin", "Điều phối giao hàng"],
    "/admin/operations": ["Admin", "Đóng gói & giao hàng"],
    "/admin/moderation": ["Admin", "Kiểm duyệt sản phẩm"],
    "/admin/feedbacks": ["Admin", "Phản hồi"],
    "/admin/reports": ["Admin", "Báo cáo"],
    "/admin/settings": ["Admin", "Cấu hình hệ thống"],

    "/supplier/dashboard": ["Supplier", "Tổng quan"],
    "/supplier/products": ["Supplier", "Sản phẩm"],
    "/supplier/products/add": ["Supplier", "Sản phẩm", "Thêm sản phẩm"],
    "/supplier/products/edit": ["Supplier", "Sản phẩm", "Chỉnh sửa"],
    "/supplier/statistic": ["Supplier", "Thống kê"],
    "/supplier/profile": ["Supplier", "Hồ sơ"],
    "/supplier/notification": ["Supplier", "Thông báo"],
    "/supplier/setting": ["Supplier", "Cài đặt"],
}
